name = "Sturq OLED"
author = "sturq"
slug = "sturq-oled"
variant = "dark"

[core]
base    = "#2A3042"
primary = "#0000EE"

[surfaces]
crust    = "#000000"
mantle   = "#000000"
base     = "#1C1C1C"
surface0 = "#2A3042"
surface1 = "#3A3A3A"
surface2 = "#586384"

[text]
text     = "#E5E5E5"
subtext1 = "#F5F5F5"
subtext0 = "#FFFFFF"
overlay2 = "#B2B2B2"
overlay1 = "#9CA7CE"
overlay0 = "#7F7F7F"

[accents]
red       = "#CD0000"
orange    = "#CD5C00"
yellow    = "#CDCD00"
green     = "#00CD00"
cyan      = "#00CDCD"
blue      = "#0000EE"
magenta   = "#CD00CD"
maroon    = "#800000"

[accents.bright]
red     = "#FF0000"
green   = "#00FF00"
yellow  = "#FFFF00"
blue    = "#5C5CFF"
magenta = "#FF00FF"
cyan    = "#00FFFF"
