#!/usr/bin/env bash
# Regenerate every artifact from formats/palette.json — the source of truth.
#   - formats/palette.toml
#   - formats/variables.css
#   - formats/base16.yaml
#   - assets/swatches/<HEX>.png   (28x28 with a hairline outline)
#   - assets/preview.png          (grouped grid)
#
# Requires: jq, imagemagick.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SRC=formats/palette.json
test -f "$SRC" || { echo "missing $SRC" >&2; exit 1; }

# ---- helpers ----
jget() { jq -r "$1" "$SRC"; }
upper() { tr '[:lower:]' '[:upper:]'; }

# ---- formats/palette.toml ----
{
  echo "name = $(jget '.name | @json')"
  echo "author = $(jget '.author | @json')"
  echo "slug = $(jget '.slug | @json')"
  echo "variant = $(jget '.variant | @json')"
  echo
  for section in core surfaces text accents; do
    echo "[$section]"
    jq -r --arg s "$section" '.[$s] | to_entries[] | select(.value | type == "string") | "\(.key) = \"\(.value)\""' "$SRC"
    echo
  done
  echo "[accents.bright]"
  jq -r '.accents.bright | to_entries[] | "\(.key) = \"\(.value)\""' "$SRC"
} > formats/palette.toml

# ---- formats/variables.css ----
{
  echo "/* Generated by scripts/build.sh — edit formats/palette.json instead. */"
  echo ":root {"
  for section in core surfaces text accents; do
    echo "  /* ${section^} */"
    jq -r --arg s "$section" '.[$s] | to_entries[] | select(.value | type == "string") | "  --sturq-\(.key): \(.value);"' "$SRC"
  done
  echo "  /* Bright ANSI */"
  jq -r '.accents.bright | to_entries[] | "  --sturq-bright-\(.key): \(.value);"' "$SRC"
  echo "}"
} > formats/variables.css

# ---- formats/base16.yaml ----
{
  cat <<EOF
# Generated by scripts/build.sh — edit formats/palette.json instead.
scheme: "$(jget .name)"
author: "$(jget .author)"
slug: "$(jget .slug)"
variant: "$(jget .variant)"

EOF
  declare -A B16
  B16[base00]=$(jget .surfaces.crust)
  B16[base01]=$(jget .surfaces.base)
  B16[base02]=$(jget .surfaces.surface0)
  B16[base03]="#7F7F7F"
  B16[base04]=$(jget .text.overlay2)
  B16[base05]=$(jget .text.text)
  B16[base06]=$(jget .text.subtext1)
  B16[base07]=$(jget .text.subtext0)
  B16[base08]=$(jget .accents.red)
  B16[base09]=$(jget .accents.orange)
  B16[base0A]=$(jget .accents.yellow)
  B16[base0B]=$(jget .accents.green)
  B16[base0C]=$(jget .accents.cyan)
  B16[base0D]=$(jget .accents.blue)
  B16[base0E]=$(jget .accents.magenta)
  B16[base0F]=$(jget .accents.maroon)
  for k in base00 base01 base02 base03 base04 base05 base06 base07 \
           base08 base09 base0A base0B base0C base0D base0E base0F; do
    hex="${B16[$k]#\#}"
    echo "$k: \"$(echo "$hex" | tr 'A-F' 'a-f')\""
  done
} > formats/base16.yaml

# ---- assets/swatches/<HEX>.png ----
rm -rf assets/swatches
mkdir -p assets/swatches
# Collect every unique hex anywhere in the palette.
hexes=$(jq -r '.. | strings | select(test("^#[0-9A-Fa-f]{6}$"))' "$SRC" \
        | sed 's/^#//' | upper | sort -u)
for hex in $hexes; do
  magick -size 28x28 "xc:#${hex}" -bordercolor "#2A2A2A" -border 1x1 \
    "assets/swatches/${hex}.png"
done

# ---- assets/preview.png ----
exec "$ROOT/scripts/gen-preview.sh"
