#!/usr/bin/env python3
"""
Regenerate every artifact from formats/palette.json.

The JSON now only carries metadata + core.{base, primary}. Surfaces,
text tiers, accents, base16Scheme — all derived via mix/lighten/darken
(mirroring sturq/nix-config:lib/palette.nix exactly).

Outputs:
  formats/palette.toml
  formats/variables.css
  formats/base16.yaml
  assets/preview.png         (via gen-preview.py)
  assets/derivation.png      (via render-derivation.py)
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = json.loads((ROOT / "formats" / "palette.json").read_text())

BASE    = SRC["core"]["base"]
PRIMARY = SRC["core"]["primary"]


def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

def rgb_to_hex(rgb):
    return "#{:02X}{:02X}{:02X}".format(*(max(0, min(255, c)) for c in rgb))

def mix(a, b, pct):
    ra, rb = hex_to_rgb(a), hex_to_rgb(b)
    return rgb_to_hex(tuple((x * (100 - pct) + y * pct) // 100 for x, y in zip(ra, rb)))

lighten = lambda c, p: mix(c, "#FFFFFF", p)
darken  = lambda c, p: mix(c, "#000000", p)


surfaces = {
    "crust":    darken(BASE, 20),
    "mantle":   darken(BASE, 10),
    "dim":      BASE,
    "surface0": lighten(BASE, 5),
    "surface1": lighten(BASE, 10),
    "surface2": lighten(BASE, 18),
}
text = {
    "text":     mix("#FFFFFF", BASE, 5),
    "subtext1": mix("#FFFFFF", BASE, 15),
    "subtext0": mix("#FFFFFF", BASE, 25),
    "overlay2": mix("#FFFFFF", BASE, 45),
    "overlay1": mix("#FFFFFF", BASE, 60),
    "overlay0": mix("#FFFFFF", BASE, 75),
}
accents = {
    "red":     darken(PRIMARY, 30),
    "orange":  darken(PRIMARY, 15),
    "yellow":  lighten(PRIMARY, 5),
    "green":   PRIMARY,
    "cyan":    lighten(PRIMARY, 25),
    "blue":    PRIMARY,
    "magenta": darken(PRIMARY, 40),
    "maroon":  darken(PRIMARY, 50),
}
bright = {
    "red":     mix(PRIMARY, "#FFFFFF", 10),
    "orange":  lighten(PRIMARY, 5),
    "yellow":  lighten(PRIMARY, 15),
    "green":   lighten(PRIMARY, 10),
    "cyan":    lighten(PRIMARY, 35),
    "blue":    lighten(PRIMARY, 15),
    "magenta": darken(PRIMARY, 25),
    "maroon":  darken(PRIMARY, 35),
}
base16 = {
    "base00": surfaces["crust"],
    "base01": surfaces["dim"],
    "base02": surfaces["surface0"],
    "base03": surfaces["surface2"],
    "base04": text["overlay2"],
    "base05": text["text"],
    "base06": text["subtext1"],
    "base07": text["subtext0"],
    "base08": accents["red"],
    "base09": accents["orange"],
    "base0A": accents["yellow"],
    "base0B": accents["green"],
    "base0C": accents["cyan"],
    "base0D": accents["blue"],
    "base0E": accents["magenta"],
    "base0F": accents["maroon"],
}


# ---- formats/palette.toml ---------------------------------------------------
def emit_toml():
    L = []
    L.append(f'# Generated by scripts/build.py — edit formats/palette.json.')
    L.append(f'name = {json.dumps(SRC["name"])}')
    L.append(f'author = {json.dumps(SRC["author"])}')
    L.append(f'slug = {json.dumps(SRC["slug"])}')
    L.append(f'variant = {json.dumps(SRC["variant"])}')
    for section, items in [("core", SRC["core"]),
                           ("surfaces", surfaces),
                           ("text", text),
                           ("accents", accents)]:
        L.append("")
        L.append(f'[{section}]')
        for k, v in items.items():
            L.append(f'{k} = "{v}"')
    L.append("")
    L.append("[accents.bright]")
    for k, v in bright.items():
        L.append(f'{k} = "{v}"')
    return "\n".join(L) + "\n"


# ---- formats/variables.css --------------------------------------------------
def emit_css():
    L = []
    L.append(f'/* Generated by scripts/build.py — edit formats/palette.json. */')
    L.append(':root {')
    L.append('  /* Core */')
    for k, v in SRC["core"].items():
        L.append(f'  --sturq-{k}: {v};')
    L.append('  /* Surfaces */')
    for k, v in surfaces.items():
        L.append(f'  --sturq-{k}: {v};')
    L.append('  /* Text & overlays */')
    for k, v in text.items():
        L.append(f'  --sturq-{k}: {v};')
    L.append('  /* Accents */')
    for k, v in accents.items():
        L.append(f'  --sturq-{k}: {v};')
    L.append('  /* Bright variants */')
    for k, v in bright.items():
        L.append(f'  --sturq-bright-{k}: {v};')
    L.append('}')
    return "\n".join(L) + "\n"


# ---- formats/base16.yaml ----------------------------------------------------
def emit_base16():
    L = []
    L.append(f'# Generated by scripts/build.py — edit formats/palette.json.')
    L.append(f'scheme: {json.dumps(SRC["name"])}')
    L.append(f'author: {json.dumps(SRC["author"])}')
    L.append(f'slug: {json.dumps(SRC["slug"])}')
    L.append(f'variant: {json.dumps(SRC["variant"])}')
    L.append('')
    for k, v in base16.items():
        L.append(f'{k}: "{v.lstrip("#").lower()}"')
    return "\n".join(L) + "\n"


# ---- write -----------------------------------------------------------------
(ROOT / "formats" / "palette.toml").write_text(emit_toml())
print(f'wrote formats/palette.toml')
(ROOT / "formats" / "variables.css").write_text(emit_css())
print(f'wrote formats/variables.css')
(ROOT / "formats" / "base16.yaml").write_text(emit_base16())
print(f'wrote formats/base16.yaml')

# ---- regenerate images -----------------------------------------------------
for script in ["gen-preview.py", "render-derivation.py"]:
    p = ROOT / "scripts" / script
    if p.exists():
        subprocess.check_call([sys.executable, str(p)])
