#!/usr/bin/env python3
"""
Regenerate every artifact from formats/palette.json — the source of
truth (only `core.{base, primary}` is canonical; everything below is
derived).

Outputs:
  formats/palette.toml
  formats/variables.css
  formats/base16.yaml
  assets/swatches/<HEX>.png    24x24 swatches for README tables
  assets/preview.png           grid overview (header image)
"""
import json
import shutil
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
SRC = json.loads((ROOT / "formats" / "palette.json").read_text())

BASE    = SRC["core"]["base"]
PRIMARY = SRC["core"]["primary"]


# ---- colour math ------------------------------------------------------------
def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

def rgb_to_hex(rgb):
    return "#{:02X}{:02X}{:02X}".format(*(max(0, min(255, c)) for c in rgb))

def mix(a, b, pct):
    ra, rb = hex_to_rgb(a), hex_to_rgb(b)
    return rgb_to_hex(tuple((x * (100 - pct) + y * pct) // 100 for x, y in zip(ra, rb)))

lighten = lambda c, p: mix(c, "#FFFFFF", p)
darken  = lambda c, p: mix(c, "#000000", p)


# ---- derivation (mirrors nix-config:lib/palette.nix) ------------------------
core = {"base": BASE, "primary": PRIMARY}

surfaces = {
    "crust":    darken(BASE, 20),
    "mantle":   darken(BASE, 10),
    "dim":      BASE,
    "surface0": lighten(BASE, 5),
    "surface1": lighten(BASE, 10),
    "surface2": lighten(BASE, 18),
}
text = {
    "text":     mix("#FFFFFF", BASE, 5),
    "subtext1": mix("#FFFFFF", BASE, 15),
    "subtext0": mix("#FFFFFF", BASE, 25),
    "overlay2": mix("#FFFFFF", BASE, 45),
    "overlay1": mix("#FFFFFF", BASE, 60),
    "overlay0": mix("#FFFFFF", BASE, 75),
}
accents = {
    "red":     darken(PRIMARY, 30),
    "orange":  darken(PRIMARY, 15),
    "yellow":  lighten(PRIMARY, 5),
    "green":   PRIMARY,
    "cyan":    lighten(PRIMARY, 25),
    "blue":    PRIMARY,
    "magenta": darken(PRIMARY, 40),
    "maroon":  darken(PRIMARY, 50),
}
bright = {
    "red":     mix(PRIMARY, "#FFFFFF", 10),
    "orange":  lighten(PRIMARY, 5),
    "yellow":  lighten(PRIMARY, 15),
    "green":   lighten(PRIMARY, 10),
    "cyan":    lighten(PRIMARY, 35),
    "blue":    lighten(PRIMARY, 15),
    "magenta": darken(PRIMARY, 25),
    "maroon":  darken(PRIMARY, 35),
}
# base16 has base + primary baked in directly (sturq/nix-config:lib/palette.nix)
base16 = {
    "base00": BASE,
    "base01": lighten(BASE, 5),
    "base02": lighten(BASE, 10),
    "base03": lighten(BASE, 18),
    "base04": text["overlay2"],
    "base05": text["text"],
    "base06": text["subtext1"],
    "base07": text["subtext0"],
    "base08": accents["red"],
    "base09": accents["orange"],
    "base0A": accents["yellow"],
    "base0B": accents["green"],
    "base0C": accents["cyan"],
    "base0D": PRIMARY,
    "base0E": accents["magenta"],
    "base0F": accents["maroon"],
}


# ---- formats ----------------------------------------------------------------
def emit_toml():
    L = ['# Generated by scripts/build.py — edit formats/palette.json.',
         f'name = {json.dumps(SRC["name"])}',
         f'author = {json.dumps(SRC["author"])}',
         f'slug = {json.dumps(SRC["slug"])}',
         f'variant = {json.dumps(SRC["variant"])}']
    for sec, items in [("core", core), ("surfaces", surfaces),
                       ("text", text), ("accents", accents)]:
        L.append("")
        L.append(f'[{sec}]')
        for k, v in items.items():
            L.append(f'{k} = "{v}"')
    L.append("")
    L.append("[accents.bright]")
    for k, v in bright.items():
        L.append(f'{k} = "{v}"')
    return "\n".join(L) + "\n"


def emit_css():
    L = ['/* Generated by scripts/build.py — edit formats/palette.json. */',
         ':root {',
         '  /* Core */']
    for k, v in core.items():
        L.append(f'  --sturq-{k}: {v};')
    L.append('  /* Surfaces */')
    for k, v in surfaces.items():
        L.append(f'  --sturq-{k}: {v};')
    L.append('  /* Text & overlays */')
    for k, v in text.items():
        L.append(f'  --sturq-{k}: {v};')
    L.append('  /* Accents */')
    for k, v in accents.items():
        L.append(f'  --sturq-{k}: {v};')
    L.append('  /* Bright variants */')
    for k, v in bright.items():
        L.append(f'  --sturq-bright-{k}: {v};')
    L.append('}')
    return "\n".join(L) + "\n"


def emit_base16():
    L = ['# Generated by scripts/build.py — edit formats/palette.json.',
         f'scheme: {json.dumps(SRC["name"])}',
         f'author: {json.dumps(SRC["author"])}',
         f'slug: {json.dumps(SRC["slug"])}',
         f'variant: {json.dumps(SRC["variant"])}', '']
    for k, v in base16.items():
        L.append(f'{k}: "{v.lstrip("#").lower()}"')
    return "\n".join(L) + "\n"


(ROOT / "formats" / "palette.toml").write_text(emit_toml())
(ROOT / "formats" / "variables.css").write_text(emit_css())
(ROOT / "formats" / "base16.yaml").write_text(emit_base16())
print("wrote formats/{palette.toml, variables.css, base16.yaml}")


# ---- swatches (24x24 PNG per unique hex) -----------------------------------
swatch_dir = ROOT / "assets" / "swatches"
if swatch_dir.exists():
    shutil.rmtree(swatch_dir)
swatch_dir.mkdir(parents=True)

all_hex = set()
for d in (core, surfaces, text, accents, bright, base16):
    all_hex.update(d.values())

for h in all_hex:
    img = Image.new("RGB", (24, 24), h)
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, 23, 23], outline="#4a4a55", width=1)
    img.save(swatch_dir / f"{h.lstrip('#').upper()}.png")
print(f"wrote {len(all_hex)} swatches")


# ---- preview.png (beautified) ----------------------------------------------
def find_font(size, bold=False):
    candidates = [
        "/data/data/com.termux/files/usr/share/fonts/TTF/DejaVuSans-Bold.ttf" if bold
            else "/data/data/com.termux/files/usr/share/fonts/TTF/DejaVuSans.ttf",
        "/system/fonts/Roboto-Bold.ttf" if bold else "/system/fonts/Roboto-Regular.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold
            else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for c in candidates:
        if Path(c).exists():
            return ImageFont.truetype(c, size)
    return ImageFont.load_default()

f_title    = find_font(40, bold=True)
f_subtitle = find_font(20)
f_section  = find_font(22, bold=True)
f_name     = find_font(15, bold=True)
f_hex      = find_font(13)

ROWS = [
    ("Core",            core,     False),
    ("Surfaces",        surfaces, False),
    ("Text & overlays", text,     False),
    ("Accents",         accents,  False),
    ("Bright variants", bright,   False),
]

SWATCH_W, SWATCH_H = 200, 110
LABEL_H = 60
PAD = 56
GAP = 12
TITLE_H = 50
SECTION_GAP = 28
HEADER_H = 160

max_cols = max(len(items) for _, items, _ in ROWS)
W = PAD * 2 + max_cols * SWATCH_W + (max_cols - 1) * GAP
H = HEADER_H + PAD + len(ROWS) * (TITLE_H + SWATCH_H + LABEL_H + SECTION_GAP) + PAD

INK     = "#F4F4F5"
INK_DIM = "#9FA1A9"
BG_PAGE = "#0a0a0f"

img = Image.new("RGB", (W, H), BG_PAGE)
d = ImageDraw.Draw(img)

# Subtle accent bar at top
d.rectangle([0, 0, W, 4], fill=PRIMARY)

# Header
d.text((PAD, 38),
       SRC["name"],
       fill=INK, font=f_title)
d.text((PAD, 96),
       f"derived from core.base ({BASE}) + core.primary ({PRIMARY})",
       fill=INK_DIM, font=f_subtitle)

y = HEADER_H + 8
for title, items, _ in ROWS:
    d.text((PAD, y), title.upper(), fill=PRIMARY, font=f_section)
    y += TITLE_H

    x = PAD
    for name, hex_ in items.items():
        d.rectangle([x, y, x + SWATCH_W, y + SWATCH_H], fill=hex_)
        # Hair-line bottom strip with name + hex
        strip_y = y + SWATCH_H + 4
        d.text((x, strip_y),       name,            fill=INK,     font=f_name)
        d.text((x, strip_y + 22),  hex_.upper(),    fill=INK_DIM, font=f_hex)
        x += SWATCH_W + GAP
    y += SWATCH_H + LABEL_H + SECTION_GAP

out = ROOT / "assets" / "preview.png"
img.save(out)
print(f"wrote {out} ({W}x{H})")


# ---- README hex tables (print to stdout for copy/paste) --------------------
def table(title, items, with_bright=False):
    print(f"\n### {title}\n")
    if with_bright:
        print("|  | Token | Hex |  | Bright | Hex |")
        print("|---|---|---|---|---|---|")
        for name, hex_ in items.items():
            bhex = bright[name]
            s1 = hex_.lstrip("#").upper()
            s2 = bhex.lstrip("#").upper()
            print(f"| ![](./assets/swatches/{s1}.png) | {name} | `{hex_.upper()}` "
                  f"| ![](./assets/swatches/{s2}.png) | bright_{name} | `{bhex.upper()}` |")
    else:
        print("|  | Token | Hex |")
        print("|---|---|---|")
        for name, hex_ in items.items():
            s = hex_.lstrip("#").upper()
            print(f"| ![](./assets/swatches/{s}.png) | {name} | `{hex_.upper()}` |")

print("\n========== README HEX TABLES ==========")
table("Core",            core)
table("Surfaces",        surfaces)
table("Text & overlays", text)
table("Accents",         accents, with_bright=True)
print("\n### Base16 mapping\n")
print("|  | Slot | Hex |")
print("|---|---|---|")
for slot, hex_ in base16.items():
    s = hex_.lstrip("#").upper()
    print(f"| ![](./assets/swatches/{s}.png) | {slot} | `{hex_.upper()}` |")
print("\n=======================================")
