#!/usr/bin/env bash
# Regenerate every artifact from formats/palette.json — the source of truth.
#
#   formats/palette.toml
#   formats/variables.css
#   formats/base16.yaml
#   assets/swatches/<HEX>.png   (28x28, hairline outline)
#   assets/preview.png          (grouped grid)
#
# Requires: jq, imagemagick.

set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
src="$root/formats/palette.json"

[[ -f "$src" ]] || { echo "missing $src" >&2; exit 1; }

q()    { jq -r "$@" "$src"; }
write() { mkdir -p "$(dirname "$1")"; cat > "$1"; }

# ----- formats/palette.toml -------------------------------------------------
{
  printf 'name = %s\nauthor = %s\nslug = %s\nvariant = %s\n\n' \
    "$(q '.name|@json')" "$(q '.author|@json')" \
    "$(q '.slug|@json')" "$(q '.variant|@json')"

  for section in core surfaces text accents; do
    printf '[%s]\n' "$section"
    q --arg s "$section" \
      '.[$s] | to_entries[] | select(.value|type=="string") | "\(.key) = \"\(.value)\""'
    printf '\n'
  done

  printf '[accents.bright]\n'
  q '.accents.bright | to_entries[] | "\(.key) = \"\(.value)\""'
} | write "$root/formats/palette.toml"

# ----- formats/variables.css ------------------------------------------------
{
  printf '/* Generated by scripts/build.sh — edit formats/palette.json. */\n'
  printf ':root {\n'

  emit() {
    local label="$1" prefix="$2" path="$3"
    printf '  /* %s */\n' "$label"
    q --arg p "$prefix" --arg path "$path" \
      'getpath($path | split(".")) | to_entries[]
       | select(.value|type=="string")
       | "  --sturq-\($p)\(.key): \(.value);"'
  }

  emit Core            ""        core
  emit Surfaces        ""        surfaces
  emit Text            ""        text
  emit Accents         ""        accents
  emit 'Bright ANSI'   bright-   accents.bright

  printf '}\n'
} | write "$root/formats/variables.css"

# ----- formats/base16.yaml --------------------------------------------------
# Map our tokens onto the base16 slots. base03 stays at the Termux
# bright-black instead of surface1 — comments want a brighter grey.
{
  cat <<EOF
# Generated by scripts/build.sh — edit formats/palette.json.
scheme: "$(q .name)"
author: "$(q .author)"
slug: "$(q .slug)"
variant: "$(q .variant)"

EOF
  q '{
       base00: .surfaces.crust,
       base01: .surfaces.dim,
       base02: .surfaces.surface0,
       base03: "#7F7F7F",
       base04: .text.overlay2,
       base05: .text.text,
       base06: .text.subtext1,
       base07: .text.subtext0,
       base08: .accents.red,
       base09: .accents.orange,
       base0A: .accents.yellow,
       base0B: .accents.green,
       base0C: .accents.cyan,
       base0D: .accents.blue,
       base0E: .accents.magenta,
       base0F: .accents.maroon
     }
     | to_entries[]
     | "\(.key): \"\(.value|sub("^#";"")|ascii_downcase)\""'
} | write "$root/formats/base16.yaml"

# ----- assets/swatches/<HEX>.png --------------------------------------------
# Every unique hex anywhere in the palette gets its own 28x28 PNG.
rm -rf "$root/assets/swatches"
mkdir -p "$root/assets/swatches"

while IFS= read -r hex; do
  magick -size 28x28 "xc:#${hex}" \
    -bordercolor "#2A2A2A" -border 1x1 \
    "$root/assets/swatches/${hex}.png"
done < <(q '..|strings|select(test("^#[0-9A-Fa-f]{6}$"))' \
         | sed 's/^#//' | tr 'a-f' 'A-F' | sort -u)

# ----- assets/preview.png ---------------------------------------------------
exec "$root/scripts/gen-preview.sh"
